#!/bin/bash
################################################
# Vilfredo easy uninstallation script
# Developed by massimiliano.alessandri@gmail.com
# Released under Affero General Public License
################################################
# Perform preliminar checks
if [ ! -x "/usr/bin/dialog" ]; then
  echo "This script requires the \"dialog\" package to be installed"
  echo "Please install it with the command \"sudo apt-get install dialog\"."
  exit
fi

if [ ! -x "/usr/bin/sudo" ]; then
  dialog --title 'Sudo command not found' --msgbox 'The "sudo" program must be installed in order to proceed.\nPlease install it with the following command:\n\napt-get install sudo' 9 70
  exit
fi

#############################################
# Get NGINX virtual host configuration folder
#############################################
if [ -d "/etc/nginx/sites-available" ]; then
	NGINX_CONF="/etc/nginx/sites-available"
elif [ -d "/etc/nginx/conf.d" ]; then
	NGINX_CONF="/etc/nginx/conf.d"
else
  dialog --backtitle "Vilfredo instance removal procedure" --title "Web server configuration error" --msgbox "A problem occurred while determining the web server configuration folder.\nPlease contact your system administrator to solve the issue." 8 70
  exit
fi

################
# Welcome screen
################
dialog --backtitle 'Vilfredo instance removal procedure' --yesno 'This procedure removes all traces of a Vilfredo instance on the server.\nIt can be useful to remove tests or wrong installations.\nNote: All data will be deleted!\nThis will not uninstall any Debian package.\nWould you like to continue?' 11 70
if [ "$?" != "0" ]; then
  exit
fi

####################
# Request parameters
####################
while true; do
  # If instance name has been specified on the command line, use it as default
  NAME=$(dialog --backtitle 'Vilfredo instance removal procedure' --inputbox "Please enter the name of the instance to be deleted." 8 70 $1 --output-fd 1)
  if [ "$?" != "0" ]; then
    exit
  fi
  if [ -z $NAME ]; then
    dialog --backtitle 'Vilfredo instance removal procedure' --title 'Empty instance name' --msgbox 'The name of the instance to be deleted has not been specified.\nPlease try again or hit the ESC key in next dialog to abort uninstallation procedure.' 7 70
  elif [ ! -d "/home/$NAME" ]; then
    dialog --backtitle 'Vilfredo instance removal procedure' --title 'Instance does not exist!' --msgbox 'The specified instance does not likely exist.\nPlease double check its name and try again.' 7 70
  else
    break
  fi
done

MYSQL_SETTINGS=`grep -e "@localhost/$NAME?" settings.cfg`

if [ -z $MYSQL_SETTINGS ]; then
  dialog --backtitle 'Vilfredo instance removal procedure' --title 'Informative message' --msgbox 'The specified instance connects to an external MySQL database.\nThus, you can stay assured it will not be deleted from this procedure.\nIf you want to actually delete the database too, you will have to perform this by hand.' 8 70
else
  while true; do
    MYSQL_ROOT_PASSWORD=$(dialog --backtitle 'Vilfredo instance removal procedure' --title 'MySQL root password' --clear --insecure --passwordbox 'Please enter the password for the MySQL "root" user, which is needed in order to connect to the server and delete the database together with all of its data.' 9 70 --output-fd 1)
    case $? in
      1)
        exit;;
      255)
        exit;;
    esac
    if [ -z $MYSQL_ROOT_PASSWORD ]; then
      dialog --backtitle 'Vilfredo instance removal procedure' --title 'Empty password' --msgbox 'No MySQL password has been entered.\nIn order to be able to delete the database together with all of its data, you must enter it.\nShould you not remember it at the moment, press the ESC key on next dialog.' 8 70
    else
      RESULT=`mysql --user=root --password=$MYSQL_ROOT_PASSWORD mysql -e 'SELECT user FROM user LIMIT 1'`
      if [ "$?" == "1" ]; then
        dialog --backtitle 'Vilfredo instance removal procedure' --title 'Wrong password' --msgbox 'An error occurred while attempting to connect to MySQL database server running on localhost.\nPlease check you entered the right password and try again.' 7 70
      else
        RESULT=`mysqlshow --user=root --password=$MYSQL_ROOT_PASSWORD | grep -v Wildcard | grep -o $NAME`
        if [ "$RESULT" != "$NAME" ]; then
          dialog --backtitle 'Vilfredo instance removal procedure' --title 'Database not existing' --msgbox "No MySQL database named \"$NAME\" exists on this server.\nIt might have been already deleted.\nInstance uninstallation will continue nevertheless." 8 70
        fi
        # Break the loop and proceed with uninstallation
        break
      fi
    fi
  done
fi

dialog --backtitle 'Vilfredo instance removal procedure' --yesno "We are about to delete the MySQL server named \"$NAME\" on this server.\nWould you like to continue?\n\nIf database contain important data, you should first make a backup.\nPress the ESC key to abort uninstallation in this case." 11 70
if [ "$?" != "0" ]; then
  exit
fi

dialog --backtitle 'Vilfredo instance removal procedure' --title 'Instance deletion in progress' --infobox 'Please wait while instance is removed from the system.\n\nThis could require a while (web services will have to be restarted in the process). Do not hit CTRL+C in the process!' 6 70 --output-fd 1

if [ ! -z $MYSQL_ROOT_PASSWORD ]
  mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e "DROP DATABASE $NAME;DROP USER $NAME@localhost"

sudo service uwsgi-pypy stop
killall -9 uwsgi-pypy
sudo service nginx stop
killall -9 nginx

if [ "$NGINX_CONF" == '/etc/nginx/conf.d' ]; then
  sudo rm -rf \
/etc/$NAME \
/var/log/$NAME \
/var/log/nginx/$NAME \
/etc/cron.hourly/$NAME \
/etc/nginx/conf.d/$NAME.conf \
/etc/uwsgi-pypy/apps-enabled/$NAME.ini \
/etc/uwsgi-pypy/apps-available/$NAME.ini \
/home/$NAME
else
  sudo rm -rf \
/etc/$NAME \
/var/log/$NAME \
/var/log/nginx/$NAME \
/etc/cron.hourly/$NAME \
/etc/nginx/sites-enabled/$NAME.conf \
/etc/nginx/sites-available/$NAME.conf \
/etc/uwsgi-pypy/apps-enabled/$NAME.ini \
/etc/uwsgi-pypy/apps-available/$NAME.ini \
/home/$NAME
fi

sudo deluser $NAME
sudo delgroup $NAME

# Note: SSL certificate is NOT deleted

sudo service uwsgi-pypy start
sudo service nginx start

# Removes temporary folder
if [ -d '/dev/shm/' ]; then
  rm -rf '/dev/shm/vilfredo'
elif [ -d '/run/shm' ]; then
  rm -rf '/run/shm/vilfredo'
elif [ -d '/tmp' ]; then
  rm -rf '/tmp/vilfredo'
else
  rm -rf './vilfredo-tmp'
fi

# Display the successful install confirmation message
dialog --backtitle 'Vilfredo instance removal procedure' --title 'Vilfredo instance removal completed' --msgbox "The Vilfredo instance named \"$NAME\" has been completely removed from this server, together with all of its data and configuration files." 7 70
